In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
from datetime import datetime
import time
import os
import warnings
warnings.filterwarnings("ignore")

######################
# METADATA
######################
sim_start = datetime.now()
sims=1000
input_folder = r'C:\Users\A4023862\OneDrive - Astellas Pharma Inc\LRF\PS22\inputs'
output_folder = r'C:\Users\A4023862\OneDrive - Astellas Pharma Inc\LRF\PS22\outputs'

######################
# READ IN DATA
######################
input_file = 'inputs_v3.xlsx'
path = os.path.join(input_folder, input_file)

sales_ci=pd.read_excel(path, sheet_name='sales', engine='openpyxl')
unc_pr=pd.read_excel(path, sheet_name='unc_pr', engine='openpyxl')
unc_pr_desc=pd.read_excel(path, sheet_name='unc_pr_desc', engine='openpyxl')
unc_pri=pd.read_excel(path, sheet_name='unc_pri', engine='openpyxl')
unc_pri_desc=pd.read_excel(path, sheet_name='unc_pri_desc', engine='openpyxl')

######################
# PREP BASELINE DATA
######################
sales_ci=sales_ci.drop_duplicates()
sales_ci=sales_ci.melt(id_vars=['product', 'region', 'units', 'indication'], 
        var_name="year", 
        value_name="sales")
sales_ci=sales_ci[(sales_ci['units'] =='Â¥')]

# Exclude indications that are not needed
exclude_ind = ['Adjustments', 'Central Adjustments', 'Total', '0', 'mPC 1L']
sales_ci=sales_ci[(~sales_ci['indication'].isin(exclude_ind))]

# Partition WW sales into 9 segments -> US, JP, CN, DE, FR, ES, IT, GB, WWex8
sales_ci_WW=sales_ci[(sales_ci['region']=='WW')]
ast8 = ['US','JP','CN', 'DE','FR','ES','IT','GB']
sales_ci_ast8=sales_ci[(sales_ci['region'].isin(ast8))]

sales_ci_WWex8=sales_ci_ast8.groupby(['product','units','indication','year']).sum().reset_index()
sales_ci_WWex8=sales_ci_WW.merge(sales_ci_WWex8, how='right', on=['product', 'units', 'indication', 'year'])
sales_ci_WWex8['sales']=sales_ci_WWex8['sales_x']-sales_ci_WWex8['sales_y']
sales_ci_WWex8['region']='WWex8'
sales_ci_WWex8 = sales_ci_WWex8[['product','region', 'units', 'indication', 'year', 'sales']]

# Generate new sales table
sales_ci_clean=pd.concat([sales_ci_ast8, sales_ci_WWex8])

# Add back non-strategic products
sales_ci_nsp=sales_ci[(sales_ci['indication']=='Non-Strategic')]
sales_ci_clean=pd.concat([sales_ci_clean, sales_ci_nsp])

# Create tag
sales_ci_clean['tag'] = sales_ci_clean['product'] + sales_ci_clean['region'] + sales_ci_clean['units'] + sales_ci_clean['indication'].astype(str)+ sales_ci_clean['year'].astype(str)

# Validation
print(sum(sales_ci_clean[(sales_ci_clean['year']==2025)]['sales']))  #18176
print(sum(sales_ci_clean[(sales_ci_clean['product']=='xtandi') & (sales_ci_clean['year']==2025)]['sales']))  #6963
print(sum(sales_ci_clean[(sales_ci_clean['product']=='mirabegron') & (sales_ci_clean['year']==2025)]['sales']))  #1223
print(sales_ci_clean['tag'].nunique()) # 2390

# Remove interim dfs from memory
del sales_ci_WW
del sales_ci_ast8
del sales_ci_WWex8
del sales_ci_nsp
del sales_ci

# Save new sales data
output_file = 'sales_clean.csv'
path = os.path.join(output_folder, output_file)
sales_ci_clean.to_csv(path)

18176.63205186673
6963.730575326161
1223.22
2300

In [2]:
%whos DataFrame

Variable         Type         Data/Info
---------------------------------------
sales_ci_clean   DataFrame                          pro<...>\n[2310 rows x 7 columns]
unc_pr           DataFrame         product region  year<...>n[1210 rows x 38 columns]
unc_pr_desc      DataFrame       uncertainties         <...>        US         0.15
unc_pri          DataFrame         product region units<...>n[1170 rows x 24 columns]
unc_pri_desc     DataFrame      uncertainties          <...>aint.  \n2  HSCT-Maint.

# Phase 1: PTRS

## Simulation

In [3]:
#############
# CREATE OUTPUT DFS FOR PHASE 1
#############
output_p1 = pd.DataFrame(columns=['tag','product', 'region', 'units', 'indication', 'year', 'sales', 'sales_RA_10', 'sales_RA_25', 'sales_RA_50', 'sales_RA_75', 'sales_RA_90']) # Output of Phase 1
scenarios_p1 = pd.DataFrame(columns=['scenario', 'tag', 'product', 'region', 'units', 'indication', 'year', 'sales', 'sim_sales']) # Scenarios of Phase 1

#############
# GENERATE SCENARIOS
#############
# Add PTRS values to sales data
sales_ci_unc = sales_ci_clean.merge(unc_pri, how='right', on=['product','region', 'units', 'indication', 'year'])

scenario_sdf=[]
product_sdf=[]
region_sdf=[]
units_sdf=[]
ind_sdf=[]
year_sdf=[]
sales_sdf=[]
tag_sdf=[]
sim_sales_sdf=[]
    
# Loop through rows
for index, row in sales_ci_unc.iterrows():
# for index, row in sales_ci_unc.iloc[29:30].iterrows():
    n=sims
    sales_ra = []
    unc_ptrs_ra = []
    
    for i in range(n):
        scenario_sdf.append(i)
        product_sdf.append(row.values[0])
        region_sdf.append(row.values[1])
        units_sdf.append(row.values[2])
        ind_sdf.append(row.values[3])
        year_sdf.append(row.values[4])
        sales_sdf.append(row.values[5])
        tag_sdf.append(row.values[6])

        # Get sales (value)
        sales = row.values[5]

        # Get PTRS Uncertainty Probability (value)
        unc_ptrs_prob=np.random.binomial(size=1, n=1, p=row.values[7])
        
        # Get Uncertainty Value (value) for others
        unc1=row.values[8]
        unc2=row.values[9]
        
        if ((unc_ptrs_prob == 1) and ((~np.isnan(unc1)) or (~np.isnan(unc2)) )):
            m=sims
            for j in range(m):

                # Get Uncertainty Probability (value) for others
                unc1_prob=np.random.randint(1,4)
                
                if ((unc1_prob == 1)):
                    sales=unc1
                
                if ((unc1_prob == 2)):
                    sales=unc2
                    
        
        # Generate RA sales
        unc_all=float(sales)*float(unc_ptrs_prob)
        sales_ra.append(unc_all)
        sim_sales_sdf.append(unc_all)
        
    # Get Product Worldwide sales by year (series)
    prod_ww_sales = sales_ci_unc.iloc[index]
    prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
    prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
    prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
    prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
    prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
    prod_ww_sales['sales_P1_RA'] = np.mean(sales_ra)
    
    # Append to sales df
    output_p1 = output_p1.append(prod_ww_sales, ignore_index=True)
    
    # Develop scenario_df
    scenarios_p1= pd.DataFrame({'scenario': scenario_sdf,'tag': tag_sdf,'product': product_sdf,'region': region_sdf, 'units': units_sdf, 
                                'indication': ind_sdf, 'year': year_sdf, 'sales': sales_sdf, 'sim_sales': sim_sales_sdf})

# Save outputs
output_p1 = output_p1[['tag','product','region', 'units', 'indication', 'year', 'sales', 'sales_RA_10', 'sales_RA_25', 'sales_RA_50','sales_RA_75', 'sales_RA_90', 'sales_P1_RA']]

# Add non-simulated tags to output and scenario dfs
sales_exP1=sales_ci_clean[~(sales_ci_clean['tag'].isin(output_p1['tag']))]
sales_exP1['sales_RA_10']=sales_exP1['sales']
sales_exP1['sales_RA_25']=sales_exP1['sales']
sales_exP1['sales_RA_50']=sales_exP1['sales']
sales_exP1['sales_RA_75']=sales_exP1['sales']
sales_exP1['sales_RA_90']=sales_exP1['sales']
sales_exP1['sales_P1_RA']=sales_exP1['sales']
output_p1=pd.concat([output_p1, sales_exP1])

# Validation
print(sum(output_p1[(output_p1['year']==2025)]['sales']))  #18176
print(sum(output_p1[(output_p1['product']=='xtandi') & (output_p1['year']==2025)]['sales'])) #6963
print(sum(output_p1[(output_p1['product']=='mirabegron') & (output_p1['year']==2025)]['sales']))  #1223
print(output_p1['tag'].nunique()) # 2300

18176.63205186673
6963.730575326161
1223.22
2300

## Prep Results for Analysis

In [4]:
# Convert PTRS results to sales df for next phase (Commercial Uncertainty)
output_p1=output_p1[['tag','product','region', 'units', 'indication', 'year', 'sales', 'sales_P1_RA']]

# Sum sales at the WW level
output_p1_ww=output_p1.groupby(['product','units','indication','year']).sum().reset_index()
output_p1_ww['region']='Total'
output_p1=pd.concat([output_p1_ww, output_p1])

# Sum sales and scenarios at the Product level, as commercial uncertainty is applied at a higher granularity
output_p1_prod=output_p1.groupby(['product','units','region','year']).sum().reset_index()
output_p1_prod['indication']='Total'
output_p1=pd.concat([output_p1_prod, output_p1])

scenarios_p1_prod=scenarios_p1[scenarios_p1['product']=='fezo'].groupby(['product','units','region','year', 'scenario']).sum().reset_index()
scenarios_p1_prod['indication']='Total'
scenarios_p1=pd.concat([scenarios_p1_prod, scenarios_p1])

# Validation
print(sum(output_p1[(output_p1['year']==2025)& (output_p1['region']!='Total') & (output_p1['indication']!='Total')]['sales']))  #18176
print(sum(output_p1[(output_p1['product']=='xtandi') & (output_p1['year']==2025) & (output_p1['region']!='Total') & (output_p1['indication']!='Total')]['sales']))  #6963
print(sum(output_p1[(output_p1['product']=='mirabegron') & (output_p1['year']==2025) & (output_p1['region']!='Total') & (output_p1['indication']!='Total')]['sales']))  #1223
print(output_p1[(output_p1['region']!='Total') & (output_p1['indication']!='Total')]['tag'].nunique()) # 2300

# Remove interim dfs from memory
del sales_exP1
del output_p1_ww
del output_p1_prod
del scenarios_p1_prod
del sales_ci_unc

output_file = 'output_p1.csv'
path = os.path.join(output_folder, output_file)
output_p1.to_csv(path)

output_file = 'scenarios_p1.csv'
path = os.path.join(output_folder, output_file)
scenarios_p1.to_csv(path)

18176.63205186673
6963.730575326161
1223.22
2300

# Phase 2: Market Events / Commercial Uncertainty

## Prep for Phase 2

In [5]:
#############
# CREATE OUTPUT DFS FOR PHASE 2
#############
output_p2 = pd.DataFrame(columns=['tag','product', 'region', 'units', 'indication', 'year', 'sales', 'sales_RA_10', 'sales_RA_25','sales_RA_50','sales_RA_75', 'sales_RA_90']) # Outputs of Phase 2
scenarios_p2 = pd.DataFrame(columns=['scenario', 'tag', 'product', 'region', 'units', 'indication', 'year', 'sales', 'sim_sales']) # Scenarios of Phase 2
output_unc_p2 = pd.DataFrame(columns=['tag','product', 'region', 'units', 'indication', 'year', 'sales']) # Uncertainties of Phase 2

#############
# PREP INPUTS DFS FOR PHASE 2
#############
# Create input df
input_p2a=output_p1[(output_p1['region']=='Total') & (output_p1['indication']=='Total')] # These do not go thru phase2
input_p2b=output_p1[(output_p1['region']!='Total') & (output_p1['indication'].isin(['Total']))] # These go thru phase2

# Validation
print(sum(input_p2a[(input_p2a['year']==2025)]['sales']))  #18176
print(sum(input_p2a[(input_p2a['product']=='xtandi') & (input_p2a['year']==2025)]['sales']))  #6963
print(sum(input_p2a[(input_p2a['product']=='mirabegron') & (input_p2a['year']==2025)]['sales']))  #1223

print(sum(input_p2b[(input_p2b['year']==2025)]['sales']))  #18176
print(sum(input_p2b[(input_p2b['product']=='xtandi') & (input_p2b['year']==2025)]['sales']))  #6963
print(sum(input_p2b[(input_p2b['product']=='mirabegron') & (input_p2b['year']==2025)]['sales']))  #1223

18176.632051866727
6963.730575326162
1223.22
18176.632051866723
6963.730575326161
1223.2200000000003

## Simulation

In [6]:
#############
# XTANDI
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'xtandi'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []
        unc1_ra = []
        unc2_ra = []
        unc3_ra = []
        unc26_ra = []
        unc29_ra = []
        
        for i in range(n):
            # Get Uncertainty Probability (value)
            unc1_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc1')]['probability'], 1, 1)
            unc2_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc2')]['probability'], 1, 1)
            unc3_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc3')]['probability'], 1, 1)
            unc26_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc26')]['probability'])
            unc29_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc29')]['probability'], 1, 1)
            
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)
            
            # Get relevant sales values for uncertainties
            unc26_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            unc29_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']

            # Get Uncertainty Quant by year (series)
            unc1=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc1']
            unc2=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc2'])*float(unc26_sales)
            unc3=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc3'])*float(unc26_sales)
            unc26=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc26'])*float(unc26_sales)
            unc29=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc29'])*float(unc29_sales)

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob) + float(unc1*unc1_prob) + float(unc2*unc2_prob) + float(unc3*unc3_prob) + float(unc26*unc26_prob) + float(unc29*unc29_prob)
            sales_ra.append(unc_all)
            
            # Generate uncertainty arrays
            unc1_ra.append(float(unc1*unc1_prob))
            unc2_ra.append(float(unc2*unc2_prob))
            unc3_ra.append(float(unc3*unc3_prob))
            unc26_ra.append(float(unc26*unc26_prob))
            unc29_ra.append(float(unc29*unc29_prob))
            
        # Get Product Region sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
        
        # Add uncertainty arrays to output_unc
        output_unc=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        output_unc['unc1_ra'] = np.mean(unc1_ra)
        output_unc['unc2_ra'] = np.mean(unc2_ra)
        output_unc['unc3_ra'] = np.mean(unc3_ra)
        output_unc['unc26_ra'] = np.mean(unc26_ra)
        output_unc['unc29_ra'] = np.mean(unc29_ra)
        
        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
        output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,0,xtandi,FR,Â¥,Total,2031,61.432580,57.645557,58.398510,59.372774,60.271772,60.984088,61.432580,59.347382,1.256032
86,0,xtandi,IT,Â¥,Total,2031,19.942742,18.738914,18.990992,19.293345,19.603485,19.827063,19.942742,19.293874,0.408758
87,0,xtandi,ES,Â¥,Total,2031,16.842266,15.846385,16.044665,16.296525,16.570401,16.764934,16.842266,16.303442,0.349098
88,0,xtandi,GB,Â¥,Total,2031,9.228120,8.675773,8.780634,8.927255,9.076348,9.169576,9.228120,8.924465,0.188973
89,0,xtandi,WWex8,Â¥,Total,2031,130.687640,123.749038,125.165181,127.116540,129.179887,130.597437,130.616109,127.194116,2.606968

In [7]:
print(sum(output_p2[(output_p2['product'] =='xtandi')]['sales']))
print(sum(output_p2[(output_p2['product'] =='xtandi')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='xtandi')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='xtandi')]['sales_RA_75']))

42655.95573277718
40797.93469474958
41859.678559650274
42807.87893527278

In [8]:
#############
# XOSPATA
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'xospata'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]


for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []
        unc4_ra = []
        unc5_ra = []
        unc6_ra = []
        unc28_ra = []
        
        for i in range(n):
            # Get Uncertainty Probability (value)
            unc4_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc4')]['probability'], 1, 1)
            unc5_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc5')]['probability'], 1, 1)
            unc6_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc6')]['probability'], 1, 1)
            unc28_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc28')]['probability'], 1, 1)

            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

            # Get relevant sales values for uncertainties
            unc4_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            unc5_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            unc6_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            unc28_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            
            # Get Uncertainty Quant by year (series)
            unc4=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc4'])*float(unc4_sales)
            unc5=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc5'])*float(unc5_sales)
            unc6=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc6'])*float(unc6_sales)
            unc28=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc28'])*float(unc28_sales)

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob) + float(unc4*unc4_prob) + float(unc5*unc5_prob) + float(unc6*unc6_prob) + float(unc28*unc28_prob)
            sales_ra.append(unc_all)
            
            # Generate uncertainty arrays
            unc4_ra.append(float(unc4*unc4_prob))
            unc5_ra.append(float(unc5*unc5_prob))
            unc6_ra.append(float(unc6*unc6_prob))
            unc28_ra.append(float(unc28*unc28_prob))
            
        # Get Product Region sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
        
        # Add uncertainty arrays to output_unc
        output_unc=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        output_unc['unc4_ra'] = np.mean(unc4_ra)
        output_unc['unc5_ra'] = np.mean(unc5_ra)
        output_unc['unc6_ra'] = np.mean(unc6_ra)
        output_unc['unc28_ra'] = np.mean(unc28_ra)
        
        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
        output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,0,xospata,FR,Â¥,Total,2031,32.290125,16.487154,18.562895,21.089162,23.530464,25.560585,29.292033,21.117340,3.388776
176,0,xospata,IT,Â¥,Total,2031,100.264447,53.116961,59.739090,66.953925,74.600058,82.292654,91.972471,67.155571,10.706029
177,0,xospata,ES,Â¥,Total,2031,23.282524,11.900749,13.351228,15.058418,16.717297,18.431644,21.019875,15.095368,2.430223
178,0,xospata,GB,Â¥,Total,2031,43.577112,22.347696,25.539725,28.599381,31.802097,34.776146,39.779466,28.645854,4.611264
179,0,xospata,WWex8,Â¥,Total,2031,301.645968,264.991295,269.208885,277.133163,283.378195,287.253780,276.056686,276.387523,8.112493

In [9]:
print(sum(output_p2[(output_p2['product'] =='xospata') & (output_p2['year'] ==2026) & (output_p2['region']!='ALL')]['sales']))
print(sum(output_p2[(output_p2['product'] =='xospata') & (output_p2['year'] ==2026) & (output_p2['region']!='ALL')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='xospata') & (output_p2['year'] ==2026) & (output_p2['region']!='ALL')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='xospata') & (output_p2['year'] ==2026) & (output_p2['region']!='ALL')]['sales_RA_75']))

1088.5645599123377
935.9884656390107
968.8728539125599
1000.6038530615594

In [10]:
#############
# PADCEV
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'padcev'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []
        unc7_ra = []
        unc8_ra = []
        unc9_ra = []
        unc10_ra = []
        unc11_ra = []
        unc12_ra = []
        unc13_ra = []
        unc14_ra = []
        
        for i in range(n):
            # Get Uncertainty Probability (value)
            unc7_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc7')]['probability'], 1, 1)
            unc8_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc8')]['probability'], 1, 1)
            unc9_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc9')]['probability'], 1, 1)
            unc10_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc10')]['probability'], 1, 1)
            unc11_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc11')]['probability'], 1, 1)
            unc12_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc12')]['probability'], 1, 1)
            unc13_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc13')]['probability'], 1, 1)
            unc14_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc14')]['probability'], 1, 1)
        
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

            # Get Uncertainty Quant by year (series)
            unc7=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc7']
            unc8=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc8']
            unc9=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc9']
            unc10=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc10']
            unc11=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc11']
            unc12=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc12']
            unc13=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc13']
            unc14=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc14']

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob) + float(unc7*unc7_prob) + float(unc8*unc8_prob) + float(unc9*unc9_prob) + float(unc10*unc10_prob) + float(unc11*unc11_prob) + float(unc12*unc12_prob) + float(unc13*unc13_prob) + float(unc14*unc14_prob)
            sales_ra.append(unc_all)
            
            # Generate uncertainty arrays
            unc7_ra.append(float(unc7*unc7_prob))
            unc8_ra.append(float(unc8*unc8_prob))
            unc9_ra.append(float(unc9*unc9_prob))
            unc10_ra.append(float(unc10*unc10_prob))
            unc11_ra.append(float(unc11*unc11_prob))
            unc12_ra.append(float(unc12*unc12_prob))
            unc13_ra.append(float(unc13*unc13_prob))
            unc14_ra.append(float(unc14*unc14_prob))

        # Get Product Worldwide sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
        
        # Add uncertainty arrays to output_unc
        output_unc=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        output_unc['unc7_ra'] = np.mean(unc7_ra)
        output_unc['unc8_ra'] = np.mean(unc8_ra)
        output_unc['unc9_ra'] = np.mean(unc9_ra)
        output_unc['unc10_ra'] = np.mean(unc10_ra)
        output_unc['unc11_ra'] = np.mean(unc11_ra)
        output_unc['unc12_ra'] = np.mean(unc12_ra)
        output_unc['unc13_ra'] = np.mean(unc13_ra)
        output_unc['unc14_ra'] = np.mean(unc14_ra)
    
        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
        output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,0,padcev,FR,Â¥,Total,2031,67.683969,56.715758,59.847417,64.770584,69.081096,71.932463,64.443686,64.502494,5.483493
266,0,padcev,IT,Â¥,Total,2031,137.397042,115.283712,122.086777,130.556050,140.341295,146.183429,130.802282,130.987839,11.030907
267,0,padcev,ES,Â¥,Total,2031,74.871373,62.580786,65.916934,70.756361,75.858834,79.271564,70.778758,70.885264,6.001560
268,0,padcev,GB,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
269,0,padcev,WWex8,Â¥,Total,2031,497.236798,416.382107,439.649785,475.163689,509.710662,529.477102,472.329429,474.202795,41.049280

In [11]:
print(sum(output_p2[(output_p2['product'] =='padcev')]['sales']))
print(sum(output_p2[(output_p2['product'] =='padcev')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='padcev')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='padcev')]['sales_RA_75']))

22941.477383758553
20391.24621330328
22195.320246991814
23998.099961099117

In [12]:
#############
# EVRENZO
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'evrenzo'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []
        unc15_ra = []
        unc16_ra = []
        unc17_ra = []
        unc18_ra = []
        
        for i in range(n):
            # Get Uncertainty Probability (value)
            unc15_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc15')]['probability'], 1, 1)
            unc16_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc16')]['probability'], 1, 1)
            unc17_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc17')]['probability'], 1, 1)
            unc18_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc18')]['probability'], 1, 1)
        
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

            # Get Uncertainty Quant by year (series)
            unc15=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc15']
            unc16=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc16']
            unc17=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc17']
            unc18=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc18']

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob) + float(unc15*unc15_prob) + float(unc16*unc16_prob) + float(unc17*unc17_prob) + float(unc18*unc18_prob)
            sales_ra.append(unc_all)
            
            # Generate uncertainty arrays
            unc15_ra.append(float(unc15*unc15_prob))
            unc16_ra.append(float(unc16*unc16_prob))
            unc17_ra.append(float(unc17*unc17_prob))
            unc18_ra.append(float(unc18*unc18_prob))

        # Get Product Worldwide sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
        
        # Add uncertainty arrays to output_unc
        output_unc=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        output_unc['unc15_ra'] = np.mean(unc15_ra)
        output_unc['unc16_ra'] = np.mean(unc16_ra)
        output_unc['unc17_ra'] = np.mean(unc17_ra)
        output_unc['unc18_ra'] = np.mean(unc18_ra)
        
        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
        output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,0,evrenzo,FR,Â¥,Total,2031,66.060153,58.169797,60.906395,66.212473,70.784106,73.678868,66.060153,65.990814,5.663869
356,0,evrenzo,IT,Â¥,Total,2031,101.517209,89.244754,93.949090,101.660234,109.146566,113.453225,101.517209,101.475745,8.746162
357,0,evrenzo,ES,Â¥,Total,2031,24.867392,21.996537,23.041506,24.945931,26.695894,27.903470,24.867392,24.930473,2.133534
358,0,evrenzo,GB,Â¥,Total,2031,58.225255,51.162248,53.420684,57.879960,62.659499,65.464998,58.225255,58.022217,5.179035
359,0,evrenzo,WWex8,Â¥,Total,2031,158.629325,139.724810,146.682933,158.558135,170.324101,177.327756,158.629325,158.518733,13.672652

In [13]:
print(sum(output_p2[(output_p2['product'] =='evrenzo')]['sales']))
print(sum(output_p2[(output_p2['product'] =='evrenzo')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='evrenzo')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='evrenzo')]['sales_RA_75']))

4451.264751048861
4100.120736509815
4437.40679128717
4774.362021811944

In [14]:
#############
# ZOLBE
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'zolbe'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []
        unc27_ra = []
        
        for i in range(n):
            # Get Uncertainty Probability (value)
            unc27_prob=np.random.triangular(0, unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc27')]['probability'], 1, 1)
            
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)
            
            # Get relevant sales values for uncertainties
            unc27_sales=input_p2b[(input_p2b['product']==product) & (input_p2b['year'] ==year) & (input_p2b['region']==region)]['sales']
            
            # Get Uncertainty Quant by year (series)
            unc27=float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc27'])*float(unc4_sales)

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob) + float(unc27*unc27_prob) 
            sales_ra.append(unc_all)
            
            # Generate uncertainty arrays
            unc27_ra.append(float(unc27*unc27_prob))

        # Get Product Worldwide sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
        
        # Add uncertainty arrays to output_unc
        output_unc=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        output_unc['unc27_ra'] = np.mean(unc27_ra)

        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
        output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,0,zolbe,FR,Â¥,Total,2031,14.478137,-54.619504,-38.792017,-21.885206,-9.770816,-1.999047,12.610457,-25.069875,19.441443
446,0,zolbe,IT,Â¥,Total,2031,19.395337,-50.843159,-34.585159,-17.502621,-5.287988,2.823918,16.932129,-20.671637,19.650643
447,0,zolbe,ES,Â¥,Total,2031,10.821708,-58.081643,-43.198561,-26.226699,-13.988637,-4.816143,9.371599,-29.224962,19.756312
448,0,zolbe,GB,Â¥,Total,2031,11.565093,-56.370124,-42.357711,-25.109619,-13.284100,-4.101701,10.223543,-28.182163,19.318522
449,0,zolbe,WWex8,Â¥,Total,2031,96.229600,74.194350,77.793555,84.445829,90.284180,94.527381,84.104670,84.188586,7.282468

In [15]:
mu=output_p2[(output_p2['product'] =='zolbe') & (output_p2['region'] =='US') & (output_p2['year'] ==2023)]['sales_P2_RA']
sigma=output_p2[(output_p2['product'] =='zolbe') & (output_p2['region'] =='US') & (output_p2['year'] ==2023)]['sales_P2_RA_SD']

np.random.normal(mu, sigma, 1)

array([3.22419081])

In [16]:
print(sum(output_p2[(output_p2['product'] =='zolbe')]['sales']))
print(sum(output_p2[(output_p2['product'] =='zolbe')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='zolbe')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='zolbe')]['sales_RA_75']))

5046.271924194486
1835.976964110824
2713.092849472979
3452.1594417321476

In [17]:
#############
# FEZO
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'fezo'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]
output_unc_p2=output_unc_p2[(output_unc_p2['product']!=product)]

for year in years:
    print(year)
    
    # Get Fezo US values, to create proportion
    fezo_base=output_p1[(output_p1['product']==product) & (output_p1['region']=='US') & (output_p1['year']==year)& (output_p1['indication']=='Total')]['sales_P1_RA']
    fezo_10 = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region']=='US')]['unc19'])
    fezo_25 = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region']=='US')]['unc20'])
    fezo_50 = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region']=='US')]['unc21'])
    fezo_75 = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region']=='US')]['unc22'])
    fezo_90 = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region']=='US')]['unc23'])
    
    for region in regions:
        # Get Product Worldwide sales by year (series) 
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year)]
        prod_ww_sales['sales_RA_10'] = float(fezo_10/fezo_base)*float(prod_ww_sales['sales_P1_RA'])
        prod_ww_sales['sales_RA_25'] = float(fezo_25/fezo_base)*float(prod_ww_sales['sales_P1_RA'])
        prod_ww_sales['sales_RA_50'] = float(fezo_50/fezo_base)*float(prod_ww_sales['sales_P1_RA'])
        prod_ww_sales['sales_RA_75'] = float(fezo_75/fezo_base)*float(prod_ww_sales['sales_P1_RA'])
        prod_ww_sales['sales_RA_90'] = float(fezo_90/fezo_base)*float(prod_ww_sales['sales_P1_RA'])
    
        prod_ww_sales['sales_P2_RA'] = prod_ww_sales['sales_RA_50']
        prod_ww_sales['sales_P2_RA_SD'] = (prod_ww_sales['sales_RA_90'] - prod_ww_sales['sales_P2_RA']) / .9

        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)

output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,0,fezo,FR,Â¥,Total,2031,56.674236,29.916186,37.464100,48.170753,62.880921,77.058512,55.654100,48.170753,32.097511
536,0,fezo,IT,Â¥,Total,2031,47.452308,25.073786,31.399954,40.373568,52.702667,64.585395,46.645619,40.373568,26.902030
537,0,fezo,ES,Â¥,Total,2031,21.534861,11.344287,14.206474,18.266462,23.844592,29.220767,21.104164,18.266462,12.171451
538,0,fezo,GB,Â¥,Total,2031,68.250000,35.989907,45.070234,57.950600,75.647294,92.703285,66.953250,57.950600,38.614095
539,0,fezo,WWex8,Â¥,Total,2031,344.303357,182.299951,228.294598,293.537614,383.176816,469.570654,339.138807,293.537614,195.592268

In [18]:
print(sum(output_p2[(output_p2['product'] =='fezo')]['sales']))
print(sum(output_p2[(output_p2['product'] =='fezo')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='fezo')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='fezo')]['sales_RA_75']))

26586.692485035557
17590.075295576527
22616.993786527608
29525.709596492026

In [19]:
#############
# MIRABEGRON
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'mirabegron'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []

        for i in range(n):
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

            # Get High,Base,Low Uncertainty
            unc_hbl_prob=np.random.randint(1,101)
            # unc_hbl_prob=1

            # Generate RA sales - High
            if (unc_hbl_prob>=75):
                sales = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc24'])*float(1+unc_base_prob)

            # Generate RA sales - Med
            if ((unc_hbl_prob>25) and (unc_hbl_prob<75)):
                sales = float(input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]['sales'])*float(1+unc_base_prob)

            # Generate RA sales - Low
            if (unc_hbl_prob<=25):
                sales = float(unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc25'])*float(1+unc_base_prob)

            sales_ra.append(sales)

         # Get Product, Region sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)

        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)

output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,0,mirabegron,FR,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
626,0,mirabegron,IT,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
627,0,mirabegron,ES,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
628,0,mirabegron,GB,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
629,0,mirabegron,WWex8,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [20]:
print(sum(output_p2[(output_p2['product'] =='mirabegron') & (output_p2['year'] ==2025)]['sales']))
print(sum(output_p2[(output_p2['product'] =='mirabegron') & (output_p2['year'] ==2025)]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='mirabegron') & (output_p2['year'] ==2025)]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='mirabegron') & (output_p2['year'] ==2025)]['sales_RA_75']))

1223.22
727.6677573346763
1221.8574491398153
1263.9884998516818

In [21]:
#############
# TACROLIMUS
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB', 'WWex8']
product = 'tacrolimus'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]

for year in years:
    print(year)
    
    for region in regions:
        n=sims
        sales_ra = []

        for i in range(n):
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)
            
            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob)
            sales_ra.append(unc_all)
            
        # Get Product Worldwide sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
    
        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,0,tacrolimus,FR,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
716,0,tacrolimus,IT,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
717,0,tacrolimus,ES,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
718,0,tacrolimus,GB,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
719,0,tacrolimus,WWex8,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [22]:
print(sum(output_p2[(output_p2['product'] =='tacrolimus')]['sales']))
print(sum(output_p2[(output_p2['product'] =='tacrolimus')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='tacrolimus')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='tacrolimus')]['sales_RA_75']))

14101.779121712712
13748.75556353159
14098.498885970752
14459.43558008097

In [23]:
#############
# LEXISCAN
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
product = 'lexiscan'

# Clear output for rerun
output_p2=output_p2[(output_p2['product']!=product)]

for year in years:
    print(year)
    n=sims
    sales_ra = []
    
    for i in range(n):
        # Get Base Uncertainty
        unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year)& (unc_pr['region'] =='US')]['unc_base']
        unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

        # Generate RA sales
        sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['year']==year) ]
        unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob)
        sales_ra.append(unc_all)

    # Get Product Worldwide sales by year (series)
    prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['year']==year) ]
    prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
    prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
    prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
    prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
    prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
    prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
    prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)

    
    # Append to sales df
    output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

2022
2023
2024
2025
2026
2027
2028
2029
2030
2031

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,0,lexiscan,WW,Â¥,Total,2027,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
726,0,lexiscan,WW,Â¥,Total,2028,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
727,0,lexiscan,WW,Â¥,Total,2029,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
728,0,lexiscan,WW,Â¥,Total,2030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
729,0,lexiscan,WW,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [24]:
print(sum(output_p2[(output_p2['product'] =='lexiscan')]['sales']))
print(sum(output_p2[(output_p2['product'] =='lexiscan')]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'] =='lexiscan')]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'] =='lexiscan')]['sales_RA_75']))

1174.7385985710891
1144.7976486331572
1175.7154935746978
1204.1031614098572

In [25]:
#############
# OTHERS
#############
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
region = 'WW'
other_products = ['evenity','cresemba','tamsulosin','suglat','ambisome','vesicare','mycamine','sujanu','symraf','cimzia','blincyto','repatha','linzess',
'vesomni','myslee/stilnox','irribow','gonax','feburic','asamax','josamycin','non prod','istodax','other merchandise products','allelock','tr','acr','blz','bonoteo','seroquel','geninax','col','inf-v','kiklin',
'ofa','regnite','srs','st','dificlir','p_aco - acofide','other astellas products']

for product in other_products:
    # Clear output for rerun
    output_p2=output_p2[(output_p2['product']!=product)]
    print(product)
    for year in years:
        n=sims
        sales_ra = []
    
        for i in range(n):
            # Get Base Uncertainty
            unc_base=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year)]['unc_base']
            unc_base_prob=np.random.uniform(low=-unc_base, high=unc_base)

            # Generate RA sales
            sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
            unc_all=float(sales['sales_P1_RA']) + float(sales['sales_P1_RA']*unc_base_prob)
            sales_ra.append(unc_all)

        # Get Product Worldwide sales by year (series)
        prod_ww_sales=input_p2b[(input_p2b['product'] ==product) & (input_p2b['region']==region) & (input_p2b['year']==year) ]
        prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
        prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
        prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
        prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
        prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
        prod_ww_sales['sales_P2_RA'] = np.mean(sales_ra)
        prod_ww_sales['sales_P2_RA_SD'] = np.std(sales_ra)
    

        # Append to sales df
        output_p2 = output_p2.append(prod_ww_sales, ignore_index=True)
    
output_p2=output_p2.fillna(0)
output_p2

evenity
cresemba
tamsulosin
suglat
ambisome
vesicare
mycamine
sujanu
symraf
cimzia
blincyto
repatha
linzess
vesomni
myslee/stilnox
irribow
gonax
feburic
asamax
josamycin
non prod
istodax
other merchandise products
allelock
tr
acr
blz
bonoteo
seroquel
geninax
col
inf-v
kiklin
ofa
regnite
srs
st
dificlir
p_aco - acofide
other astellas products

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P2_RA_SD
0,0,xtandi,US,Â¥,Total,2022,3186.729835,2179.155622,3039.882323,3110.150364,3170.038457,3208.673464,3110.875069,2940.080654,389.954871
1,0,xtandi,JP,Â¥,Total,2022,438.632820,425.150657,429.080782,435.276464,441.184715,445.783676,438.632820,435.242364,7.426558
2,0,xtandi,CN,Â¥,Total,2022,60.320040,58.458229,59.010178,59.894303,60.852792,61.281772,60.320040,59.885877,1.043073
3,0,xtandi,DE,Â¥,Total,2022,518.114617,502.019554,506.842045,514.528143,522.027300,526.647810,518.114617,514.339877,9.006654
4,0,xtandi,FR,Â¥,Total,2022,260.226710,251.971464,254.273037,258.412614,261.917566,264.375205,260.226710,258.267163,4.533043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1125,0,other astellas products,WW,Â¥,Total,2027,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1126,0,other astellas products,WW,Â¥,Total,2028,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1127,0,other astellas products,WW,Â¥,Total,2029,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1128,0,other astellas products,WW,Â¥,Total,2030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1129,0,other astellas products,WW,Â¥,Total,2031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [26]:
print(sum(output_p2[(output_p2['product'].isin(other_products))]['sales']))
print(sum(output_p2[(output_p2['product'].isin(other_products))]['sales_RA_25']))
print(sum(output_p2[(output_p2['product'].isin(other_products))]['sales_RA_50']))
print(sum(output_p2[(output_p2['product'].isin(other_products))]['sales_RA_75']))

9797.389256678245
9306.792065951659
9798.695896574003
10289.642919889586

## Prep Results for Analysis

In [27]:
# Add WW sales to output
output_p2a=output_p2
output_p2a=output_p2a.groupby(['product','units','indication','year']).sum().reset_index()
output_p2a['region']='ALL'
output_p2 = output_p2.append(output_p2a, ignore_index=True)

# Consolidate uncertainty output
output_unc_p2=output_unc_p2.groupby(['product','units','indication','year', 'region']).max().reset_index()

# Remove interim dfs from memory
del input_p2a 
del input_p2b 
del sales
del prod_ww_sales
del output_unc
del output_p2a

output_file = 'output_p2.csv'
path = os.path.join(output_folder, output_file)
output_p2.to_csv(path)

output_file = 'output_unc_p2.csv'
path = os.path.join(output_folder, output_file)
output_unc_p2.to_csv(path)

output_file = 'scenarios_p2.csv'
path = os.path.join(output_folder, output_file)
scenarios_p2.to_csv(path)

In [28]:
%whos DataFrame

Variable         Type         Data/Info
---------------------------------------
output_p1        DataFrame                          pro<...>\n[4550 rows x 8 columns]
output_p2        DataFrame          tag product region <...>n[1620 rows x 15 columns]
output_unc_p2    DataFrame         product units indica<...>\n[450 rows x 30 columns]
sales_ci_clean   DataFrame                          pro<...>\n[2310 rows x 7 columns]
scenarios_p1     DataFrame            product units reg<...>1270000 rows x 9 columns]
scenarios_p2     DataFrame    Empty DataFrame\nColumns:<...>es, sim_sales]\nIndex: []
unc_pr           DataFrame         product region  year<...>n[1210 rows x 38 columns]
unc_pr_desc      DataFrame       uncertainties         <...>        US         0.15
unc_pri          DataFrame         product region units<...>n[1170 rows x 24 columns]
unc_pri_desc     DataFrame      uncertainties          <...>aint.  \n2  HSCT-Maint.

# Phase 3: Above Brand

## Prep for Phase 3 and Simulation

In [35]:
# Create output dfs
output_p3 = pd.DataFrame(columns=['tag','product', 'region', 'units', 'indication', 'year', 'sales', 'sales_RA_10', 'sales_RA_25','sales_RA_50','sales_RA_75', 'sales_RA_90', 
                                  'sales_P1_RA', 'sales_P2_RA', 'sales_P3_RA']) # Outputs of Phase 3

scenarios_p3 = pd.DataFrame(columns=['scenario', 'tag', 'product', 'region', 'units', 'indication', 'year', 'sales', 'sim_sales']) # Scenarios of Phase 3
output_unc_p3 = pd.DataFrame(columns=['tag','product', 'region', 'units', 'indication', 'year', 'sales', 'variable', 'value']) # Uncertainties of Phase 3

# Inputs
years = [2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031]
regions = ['US', 'JP', 'CN', 'DE', 'FR', 'IT', 'ES', 'GB']
products = ['evrenzo', 'fezo', 'mirabegron', 'padcev', 'tacrolimus', 'xospata', 'xtandi', 'zolbe']
input_p3a=output_p2[~(output_p2['region'].isin(regions))] # These do not go thru phase3
input_p3b=output_p2[(output_p2['region'].isin(regions))] # These go thru phase3

for product in products:
    print(product)

    for year in years:

        for region in regions:
            n=sims
            n=1000
            sales_ra = []
            unc_ab1_ra = []
            unc_ab2_ra = []
            unc_ab3_ra = []
            unc_ab4_ra = []
            unc_ab5_ra = []

            for i in range(n):
                # Get Above Brand Uncertainty Probability (value)
                unc_ab1_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc_ab1')]['probability'])
                unc_ab2_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc_ab2')]['probability'])
                unc_ab3_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc_ab3')]['probability'])
                unc_ab4_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc_ab4')]['probability'])
                unc_ab5_prob=np.random.binomial(size=1, n=1, p=unc_pr_desc[(unc_pr_desc['uncertainties'] == 'unc_ab5')]['probability'])
                
                # Get sales from phase 2
                # sales=input_p3b[(input_p3b['product'] ==product) & (input_p3b['region']==region) & (input_p3b['year']==year) ]
                mu=float(input_p3b[(input_p3b['product'] ==product) & (input_p3b['region']==region) & (input_p3b['year']==year) ]['sales_P2_RA'])
                sigma=float(input_p3b[(input_p3b['product'] ==product) & (input_p3b['region']==region) & (input_p3b['year']==year) ]['sales_P2_RA_SD'])
                sales = np.random.normal(mu, (sigma/1.8), 1)

                # Get Uncertainty Quant by year (series)
                unc_ab1=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_ab1']*float(sales)*unc_ab1_prob
                unc_ab2=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_ab2']*float(sales)*unc_ab2_prob
                unc_ab3=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_ab3']*float(sales)*unc_ab3_prob
                unc_ab4=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_ab4']*float(sales)*unc_ab4_prob
                unc_ab5=unc_pr[(unc_pr['product'] ==product) & (unc_pr['year'] ==year) & (unc_pr['region'] ==region)]['unc_ab5']*float(sales)*unc_ab5_prob
                
                # Generate RA sales
                unc_all=float(sales) + unc_ab1 + unc_ab2 + unc_ab3 + unc_ab4 + unc_ab5
                sales_ra.append(unc_all)
                
                # Generate uncertainty arrays
                unc_ab1_ra.append(float(unc_ab1))
                unc_ab2_ra.append(float(unc_ab2))
                unc_ab3_ra.append(float(unc_ab3))
                unc_ab4_ra.append(float(unc_ab4))
                unc_ab5_ra.append(float(unc_ab5))
            
            # Get Product Worldwide sales by year (series)
            prod_ww_sales=input_p3b[(input_p3b['product'] ==product) & (input_p3b['region']==region) & (input_p3b['year']==year) ]
            prod_ww_sales['sales_RA_10'] = np.percentile(sales_ra, 10)
            prod_ww_sales['sales_RA_25'] = np.percentile(sales_ra, 25)
            prod_ww_sales['sales_RA_50'] = np.percentile(sales_ra, 50)
            prod_ww_sales['sales_RA_75'] = np.percentile(sales_ra, 75)
            prod_ww_sales['sales_RA_90'] = np.percentile(sales_ra, 90)
            prod_ww_sales['sales_P3_RA'] = np.mean(sales_ra)
            prod_ww_sales['sales_P3_RA_SD'] = np.std(sales_ra)
            
            # Add uncertainty arrays to output_unc
            output_unc=input_p3b[(input_p3b['product'] ==product) & (input_p3b['region']==region) & (input_p3b['year']==year) ][['tag', 'product', 'region', 'units', 'indication', 'year', 'sales','sales_P1_RA', 'sales_P2_RA']]
            output_unc['unc_ab1_ra'] = np.mean(unc_ab1_ra)
            output_unc['unc_ab2_ra'] = np.mean(unc_ab2_ra)
            output_unc['unc_ab3_ra'] = np.mean(unc_ab3_ra)
            output_unc['unc_ab4_ra'] = np.mean(unc_ab4_ra)
            output_unc['unc_ab5_ra'] = np.mean(unc_ab5_ra)

            # Append to sales df
            output_p3 = output_p3.append(prod_ww_sales, ignore_index=True)
            output_unc_p2 = output_unc_p2.append(output_unc, ignore_index=True)
            
output_p3=output_p3.fillna(0)
output_p3

evrenzo
fezo
mirabegron
padcev
tacrolimus
xospata
xtandi
zolbe

,tag,product,region,units,indication,year,sales,sales_RA_10,sales_RA_25,sales_RA_50,sales_RA_75,sales_RA_90,sales_P1_RA,sales_P2_RA,sales_P3_RA,sales_P2_RA_SD,sales_P3_RA_SD
0,0,evrenzo,US,Â¥,Total,2022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0,evrenzo,JP,Â¥,Total,2022,55.767542,48.460301,50.079674,53.010442,56.166332,58.121563,55.767542,55.931584,53.158387,4.847947,3.735674
2,0,evrenzo,CN,Â¥,Total,2022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0,evrenzo,DE,Â¥,Total,2022,16.820283,13.610098,14.076945,14.772079,16.321581,17.255938,16.820283,16.783180,15.155725,1.441919,1.390379
4,0,evrenzo,FR,Â¥,Total,2022,0.866087,0.684313,0.711044,0.750159,0.827502,0.873717,0.866087,0.849472,0.767218,0.073780,0.071929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,0,zolbe,DE,Â¥,Total,2031,36.749689,-16.668069,-10.483630,-4.221743,2.215486,8.214496,31.641483,-4.813928,-4.100645,19.068978,9.707732
636,0,zolbe,FR,Â¥,Total,2031,14.478137,-35.570228,-29.198301,-22.530639,-16.174154,-10.256054,12.610457,-25.069875,-22.706378,19.441443,9.770689
637,0,zolbe,IT,Â¥,Total,2031,19.395337,-31.429709,-25.114019,-17.797317,-11.933663,-5.858601,16.932129,-20.671637,-18.499533,19.650643,9.762674
638,0,zolbe,ES,Â¥,Total,2031,10.821708,-39.769331,-32.765710,-26.168431,-18.906788,-13.484774,9.371599,-29.224962,-26.157693,19.756312,10.195673
639,0,zolbe,GB,Â¥,Total,2031,11.565093,-37.587420,-31.506486,-25.466805,-18.995713,-13.086754,10.223543,-28.182163,-25.391666,19.318522,9.602069

## Prep Results for Analysis

In [36]:
# Update output uncertainty df for PTRS
output_unc_p2=output_unc_p2.groupby(['product','units','indication','year', 'region']).max().reset_index()
output_unc_p2['unc_ptrs'] = output_unc_p2['sales_P1_RA'] - output_unc_p2['sales']

# Update output uncertainty df for PTRS
output_unc_p2=output_unc_p2.fillna(0)

# Select columns needed
output_unc_p3=output_unc_p2[['tag', 'product', 'region', 'units', 'indication', 'year', 'sales',
                             'unc_ptrs','unc1_ra', 'unc2_ra', 'unc3_ra', 'unc4_ra',
                             'unc5_ra', 'unc6_ra', 'unc7_ra', 'unc8_ra', 'unc9_ra', 'unc10_ra',
                             'unc11_ra', 'unc12_ra', 'unc13_ra', 'unc14_ra', 'unc15_ra', 'unc16_ra',
                             'unc17_ra', 'unc18_ra', 'unc26_ra', 'unc27_ra', 'unc28_ra', 'unc29_ra',
                             'unc_ab1_ra', 'unc_ab2_ra','unc_ab3_ra', 'unc_ab4_ra', 'unc_ab5_ra']]

# Pivot table
id_vars=['tag', 'product', 'region', 'units', 'indication', 'year', 'sales']
value_vars=['unc_ptrs','unc1_ra', 'unc2_ra', 'unc3_ra', 'unc4_ra',
            'unc5_ra', 'unc6_ra', 'unc7_ra', 'unc8_ra', 'unc9_ra', 'unc10_ra',
            'unc11_ra', 'unc12_ra', 'unc13_ra', 'unc14_ra', 'unc15_ra', 'unc16_ra',
            'unc17_ra', 'unc18_ra', 'unc26_ra', 'unc27_ra', 'unc28_ra', 'unc29_ra', 
            'unc_ab1_ra', 'unc_ab2_ra','unc_ab3_ra', 'unc_ab4_ra', 'unc_ab5_ra']

output_unc_p3=pd.melt(output_unc_p3, id_vars=id_vars, value_vars=value_vars)

# # Merge uncertainty name to output_unc_p22
# output_unc_p22=output_unc_p22.merge(unc_pr_desc, how='left', left_on='lkey', right_on='rkey')

# Add back tags that did not go through phase 3
input_p3a['sales_P3_RA']=input_p3a['sales_P2_RA']
output_p3=pd.concat([output_p3, input_p3a[input_p3a['region']!='ALL']], ignore_index=True, axis=0)

# Add WW sales to output
output_phase3_agg=output_p3
output_phase3_agg=output_phase3_agg.groupby(['product','units','indication','year']).sum().reset_index()
output_phase3_agg['region']='ALL'
output_p3 = output_p3.append(output_phase3_agg, ignore_index=True)

# Remove interim dfs from memory
del prod_ww_sales
del sales
del input_p3a 
del input_p3b 
del output_phase3_agg

output_file = 'output_p3.csv'
path = os.path.join(output_folder, output_file)
output_p3.to_csv(path)

output_file = 'output_unc_p3.csv'
path = os.path.join(output_folder, output_file)
output_unc_p3.to_csv(path)

output_file = 'scenarios_p3.csv'
path = os.path.join(output_folder, output_file)
scenarios_p3.to_csv(path)

In [37]:
%whos DataFrame

Variable         Type         Data/Info
---------------------------------------
metatdata_df     DataFrame                             <...>                     1352
output_p1        DataFrame                          pro<...>\n[4550 rows x 8 columns]
output_p2        DataFrame          tag product region <...>n[1620 rows x 15 columns]
output_p3        DataFrame          tag  product region<...>n[1620 rows x 17 columns]
output_unc       DataFrame         tag product region u<...>        0.0         0.0
output_unc_p2    DataFrame         product units indica<...>\n[690 rows x 37 columns]
output_unc_p3    DataFrame           tag  product regio<...>n[19320 rows x 9 columns]
sales_ci_clean   DataFrame                          pro<...>\n[2310 rows x 7 columns]
scenarios_p1     DataFrame            product units reg<...>1270000 rows x 9 columns]
scenarios_p2     DataFrame    Empty DataFrame\nColumns:<...>es, sim_sales]\nIndex: []
scenarios_p3     DataFrame    Empty DataFrame\nColumns:<...>es, sim_sales]\nIndex: []
unc_pr           DataFrame         product region  year<...>n[1210 rows x 38 columns]
unc_pr_desc      DataFrame       uncertainties         <...>        US         0.15
unc_pri          DataFrame         product region units<...>n[1170 rows x 24 columns]
unc_pri_desc     DataFrame      uncertainties          <...>aint.  \n2  HSCT-Maint.

# Metadata

In [38]:
sim_end = datetime.now()
td =  sim_end - sim_start
td_mins = int(round(td.total_seconds() / 60))
metatdata = {'sim_start': sim_start, 'sim_end': sim_end, 'sims_run': sims, 'sim_time': td_mins}
metatdata_df=pd.DataFrame.from_dict(metatdata, orient='index')

output_file = 'metatdata.csv'
path = os.path.join(output_folder, output_file)
metatdata_df.to_csv(path)